//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities : DbContext
    {
        public SchoolDBEntities()
            : base("name=SchoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassTb> ClassTbs { get; set; }
        public virtual DbSet<StudentTb> StudentTbs { get; set; }
        public virtual DbSet<AttendenceValue> AttendenceValues { get; set; }
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<TeacherTb> TeacherTbs { get; set; }
        public virtual DbSet<TeacherAttendenceTb> TeacherAttendenceTbs { get; set; }
        public virtual DbSet<TeacherFeeTb> TeacherFeeTbs { get; set; }
    }
}
