//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAttendenceTb
    {
        public int t_a_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public int teacherId { get; set; }
        public string Remarks { get; set; }
    
        public virtual TeacherTb TeacherTb { get; set; }
        public virtual AttendenceValue AttendenceValue { get; set; }
    }
}
