//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTb()
        {
            this.TeacherAttendenceTbs = new HashSet<TeacherAttendenceTb>();
            this.TeacherFeeTbs = new HashSet<TeacherFeeTb>();
        }
    
        public int t_id { get; set; }
        public string T_Fname { get; set; }
        public string T_Lname { get; set; }
        public System.DateTime T_DOB { get; set; }
        public long T_Phone { get; set; }
        public string T_Address { get; set; }
        public int t_Cid { get; set; }
    
        public virtual ClassTb ClassTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherAttendenceTb> TeacherAttendenceTbs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherFeeTb> TeacherFeeTbs { get; set; }
    }
}
